/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as GatesRouteImport } from './routes/gates'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ReplicationsRouteImport } from './routes/replications'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as RestoresRouteImport } from './routes/restores'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as SnapshotsRouteImport } from './routes/snapshots'
import { Route as TopologyRouteImport } from './routes/topology'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesRoute = GatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplicationsRoute = ReplicationsRouteImport.update({
  id: '/replications',
  path: '/replications',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoresRoute = RestoresRouteImport.update({
  id: '/restores',
  path: '/restores',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsRoute = SnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/gates': typeof GatesRoute
  '/maintenance': typeof MaintenanceRoute
  '/policies': typeof PoliciesRoute
  '/replications': typeof ReplicationsRoute
  '/repositories': typeof RepositoriesRoute
  '/restores': typeof RestoresRoute
  '/schedules': typeof SchedulesRoute
  '/snapshots': typeof SnapshotsRoute
  '/topology': typeof TopologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/gates': typeof GatesRoute
  '/maintenance': typeof MaintenanceRoute
  '/policies': typeof PoliciesRoute
  '/replications': typeof ReplicationsRoute
  '/repositories': typeof RepositoriesRoute
  '/restores': typeof RestoresRoute
  '/schedules': typeof SchedulesRoute
  '/snapshots': typeof SnapshotsRoute
  '/topology': typeof TopologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/gates': typeof GatesRoute
  '/maintenance': typeof MaintenanceRoute
  '/policies': typeof PoliciesRoute
  '/replications': typeof ReplicationsRoute
  '/repositories': typeof RepositoriesRoute
  '/restores': typeof RestoresRoute
  '/schedules': typeof SchedulesRoute
  '/snapshots': typeof SnapshotsRoute
  '/topology': typeof TopologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctor'
    | '/gates'
    | '/maintenance'
    | '/policies'
    | '/replications'
    | '/repositories'
    | '/restores'
    | '/schedules'
    | '/snapshots'
    | '/topology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doctor'
    | '/gates'
    | '/maintenance'
    | '/policies'
    | '/replications'
    | '/repositories'
    | '/restores'
    | '/schedules'
    | '/snapshots'
    | '/topology'
  id:
    | '__root__'
    | '/'
    | '/doctor'
    | '/gates'
    | '/maintenance'
    | '/policies'
    | '/replications'
    | '/repositories'
    | '/restores'
    | '/schedules'
    | '/snapshots'
    | '/topology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorRoute: typeof DoctorRoute
  GatesRoute: typeof GatesRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PoliciesRoute: typeof PoliciesRoute
  ReplicationsRoute: typeof ReplicationsRoute
  RepositoriesRoute: typeof RepositoriesRoute
  RestoresRoute: typeof RestoresRoute
  SchedulesRoute: typeof SchedulesRoute
  SnapshotsRoute: typeof SnapshotsRoute
  TopologyRoute: typeof TopologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates': {
      id: '/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof GatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replications': {
      id: '/replications'
      path: '/replications'
      fullPath: '/replications'
      preLoaderRoute: typeof ReplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restores': {
      id: '/restores'
      path: '/restores'
      fullPath: '/restores'
      preLoaderRoute: typeof RestoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots': {
      id: '/snapshots'
      path: '/snapshots'
      fullPath: '/snapshots'
      preLoaderRoute: typeof SnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorRoute: DoctorRoute,
  GatesRoute: GatesRoute,
  MaintenanceRoute: MaintenanceRoute,
  PoliciesRoute: PoliciesRoute,
  ReplicationsRoute: ReplicationsRoute,
  RepositoriesRoute: RepositoriesRoute,
  RestoresRoute: RestoresRoute,
  SchedulesRoute: SchedulesRoute,
  SnapshotsRoute: SnapshotsRoute,
  TopologyRoute: TopologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
