import js from "@eslint/js";
import jsxA11y from "eslint-plugin-jsx-a11y";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      // Generated by `cargo xtask gen-ui-types`; byte-gated by `mise run gen-check`.
      "src/api/types/**",
      // Generated by @tanstack/router-plugin on every dev/build run.
      "src/routeTree.gen.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
      globals: globals.browser,
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks, "react-refresh": reactRefresh },
    rules: {
      ...reactHooks.configs.flat.recommended.rules,
      "react-refresh/only-export-components": [
        "error",
        { allowConstantExport: true, allowExportNames: ["Route"] },
      ],
      // The generated enum unions are heterogeneous (string | object); a switch
      // over the string arm must name every literal so a new variant fails to
      // compile instead of falling through to whatever the default renders.
      "@typescript-eslint/switch-exhaustiveness-check": [
        "error",
        { considerDefaultExhaustiveForUnions: false, requireDefaultForNonUnion: true },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true, allowBoolean: true },
      ],
      "@typescript-eslint/no-unnecessary-condition": [
        "error",
        // Defensive checks on server data are the point, not noise: a newer
        // server may send a value this bundle has never seen.
        { allowConstantLoopConditions: true },
      ],
      // Every request goes through src/api/client.ts, which owns problem
      // detection, the CSRF marker and abort pass-through. A bare fetch in a
      // component is a request that can render `[object Object]`.
      "no-restricted-globals": [
        "error",
        { name: "fetch", message: "Use apiFetch/apiPost/apiDelete from src/api/client.ts." },
      ],
    },
  },
  {
    files: ["**/*.tsx"],
    ...jsxA11y.flatConfigs.recommended,
  },
  {
    files: ["src/api/client.ts", "src/**/*.test.{ts,tsx}", "src/test-setup.ts"],
    rules: { "no-restricted-globals": "off" },
  },
  {
    // TanStack file routes export `Route` and keep their component local by
    // convention; the router plugin owns their HMR, not react-refresh.
    files: ["src/routes/**/*.tsx"],
    rules: { "react-refresh/only-export-components": "off" },
  },
  {
    files: ["**/*.js", "vite.config.ts"],
    ...tseslint.configs.disableTypeChecked,
  },
);
