// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapshotRefView } from "./SnapshotRefView";

/**
 * What a mutating action created, returned so the SPA can navigate straight to
 * the new object instead of polling a list.
 */
export type ActionReceipt = {
/**
 * Which action ran, e.g. `snapshotNow`.
 */
kind: string,
/**
 * The resources the action created.
 */
created: Array<SnapshotRefView>,
/**
 * RFC3339 timestamp of when the action was accepted.
 */
requestedAt?: string | null,
/**
 * Anything the user should know about the outcome — e.g. that a fan-out
 * created fewer snapshots than repositories because some were suspended.
 */
note?: string | null, };
