// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which namespaces a `ClusterRepository` admits, read from its spec.
 *
 * Named rather than counted: the controller's `status.allowedNamespaceCount`
 * writes `-1` for "all" and `0` for an unresolved selector, and neither is a
 * count a person can read. Exhaustive over `AllowedNamespaces`.
 */
export type AdmittedNamespacesView = "all" | "none" | { "listed": {
/**
 * How many namespaces the list names.
 */
count: number, } } | { "selector": {
/**
 * The selector, in `kubectl -l` form.
 */
selector: string, } };
