// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The coarse per-verb permissions the SPA uses to enable or hide controls.
 *
 * Each flag is the result of a `SelfSubjectAccessReview`-style check performed
 * server-side for the caller — it is a UI affordance, never the authorization
 * itself, which the apiserver always re-enforces on the real request.
 *
 * # One flag per (verb, resource) the API actually writes
 *
 * The flags are named after the review that produced them, not after a button,
 * because several buttons share one review and two buttons can share one name
 * while asking different questions. Every mutating endpoint maps onto one:
 *
 * | endpoint | flag |
 * |---|---|
 * | `POST /actions/snapshot-now` | [`Self::create_snapshots`] |
 * | `POST /actions/restore` | [`Self::create_restores`] |
 * | `DELETE /snapshots/{ns}/{name}` | [`Self::delete_snapshots`] |
 * | `POST /actions/suspend` `kind: policy` | [`Self::patch_policies`] |
 * | `POST /actions/suspend` `kind: schedule` | [`Self::patch_schedules`] |
 * | `POST /actions/suspend` `kind: repository` | [`Self::patch_repositories`] |
 * | `POST /actions/suspend` `kind: cluster-repository` | [`Self::patch_cluster_repositories`] |
 * | `POST /actions/suspend` `kind: replication` | [`Self::patch_repository_replications`] |
 * | `POST /actions/suspend` `kind: snapshot-replication` | [`Self::patch_snapshot_replications`] |
 * | `POST /actions/maintenance-run` | [`Self::patch_maintenances`] |
 * | `POST /actions/replication-run` | [`Self::patch_repository_replications`] or [`Self::patch_snapshot_replications`], by the kind the request names or detection finds |
 * | `POST /actions/scan-catalog` | [`Self::patch_repositories`] or [`Self::patch_cluster_repositories`], by `kind` |
 * | `POST /snapshots/{ns}/{name}/session` | [`Self::create_session_jobs`] **and** [`Self::exec_sessions`] |
 * | `DELETE /snapshots/{ns}/{name}/session`, `DELETE /repositories/{kind}/{name}/session` | [`Self::delete_session_jobs`] |
 * | `GET …/tree`, `GET …/file` | [`Self::exec_sessions`] |
 *
 * Starting a browse session takes **two** grants, and the SPA must require
 * both: the session is a `batch/v1` Job the UI creates, and reading through it
 * is a `pods/exec`. A user holding `pods/exec` but not `create jobs` was
 * previously shown an enabled Browse button that 403'd on click, which is the
 * exact failure these flags exist to prevent.
 *
 * # These answers are namespace-scoped
 *
 * Every flag except [`Self::patch_cluster_repositories`] is the answer for the
 * namespace `/me` was asked about (`GET /api/v1/me?namespace=`). With no
 * `?namespace=` the review is **cluster-scoped**, so a user holding only a
 * namespaced `RoleBinding` gets all-`false` and a UI where every control is
 * disabled with a reason that is not true. **The SPA must re-fetch `/me` for
 * each namespace it scopes to**, and must not cache one answer across a
 * namespace switch.
 *
 * [`Self::patch_cluster_repositories`] is asked cluster-scoped whatever
 * `?namespace=` says, because `ClusterRepository` is a cluster-scoped resource:
 * a namespaced review of it would report a `RoleBinding` grant that cannot
 * actually authorize the write.
 */
export type Capabilities = {
/**
 * May create `Snapshot` resources (the "snapshot now" action).
 */
createSnapshots: boolean,
/**
 * May delete `Snapshot` resources.
 */
deleteSnapshots: boolean,
/**
 * May create `Restore` resources.
 */
createRestores: boolean,
/**
 * May patch `SnapshotPolicy` resources (suspend/resume).
 */
patchPolicies: boolean,
/**
 * May patch `SnapshotSchedule` resources (suspend/resume).
 */
patchSchedules: boolean,
/**
 * May patch `Repository` resources (suspend/resume, catalog scan).
 */
patchRepositories: boolean,
/**
 * May patch `ClusterRepository` resources (suspend/resume, catalog scan).
 *
 * Always the cluster-scoped answer — see the type docs.
 */
patchClusterRepositories: boolean,
/**
 * May patch `Maintenance` resources (request a manual run).
 */
patchMaintenances: boolean,
/**
 * May patch `RepositoryReplication` resources (suspend/resume, run now).
 */
patchRepositoryReplications: boolean,
/**
 * May patch `SnapshotReplication` resources (suspend/resume, run now).
 */
patchSnapshotReplications: boolean,
/**
 * May create the `batch/v1` Job a browse session runs in.
 *
 * Starting a session needs this **and** [`Self::exec_sessions`]; reading
 * through an already-running one needs only the latter.
 */
createSessionJobs: boolean,
/**
 * May delete a browse session's Job — the "stop session" control, on both
 * the snapshot and the repository detail.
 */
deleteSessionJobs: boolean,
/**
 * May exec into a browse session's mover pod, which is what reading a
 * directory or streaming a file costs.
 */
execSessions: boolean, };
