// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Repository.status.catalog` — what a catalog scan found in the repository.
 */
export type CatalogView = {
/**
 * Kopia snapshots discovered and adopted as `Snapshot` resources.
 */
discoveredBackupCount?: number | null,
/**
 * Kopia snapshots present in the repository that no kopiur identity claims.
 */
foreignSnapshotCount?: number | null,
/**
 * RFC3339 timestamp of the last catalog scan.
 */
lastRefreshAt?: string | null, };
