// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * View of `status.catalog.coverage` (#476): whether `discoveredBackupCount`
 * is the whole repository or only the newest window of it.
 */
export type CatalogCoverageView = "complete" | "capped" | "partial" | { "unknown": {
/**
 * The value exactly as the operator wrote it.
 */
raw: string, } };
