// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `status.conditions[]` entry, flattened for display.
 */
export type ConditionView = {
/**
 * `conditions[].type`, e.g. `Ready`.
 */
type: string,
/**
 * `conditions[].status` — `True`, `False`, or `Unknown`.
 */
status: string,
/**
 * `conditions[].reason`.
 */
reason?: string | null,
/**
 * `conditions[].message`.
 */
message?: string | null,
/**
 * `conditions[].lastTransitionTime` as RFC3339.
 */
lastTransitionTime?: string | null, };
