// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryKind } from "./EntryKind";

/**
 * One entry in a browsed snapshot directory.
 */
export type DirEntryView = {
/**
 * The entry's basename.
 */
name: string,
/**
 * What the entry is.
 */
kind: EntryKind,
/**
 * Size in bytes, for files.
 */
size?: number | null,
/**
 * RFC3339 modification time.
 */
mtime?: string | null,
/**
 * Unix mode as kopia rendered it, e.g. `drwxr-xr-x`.
 */
mode?: string | null, };
