// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirEntryView } from "./DirEntryView";
import type { SessionInfo } from "./SessionInfo";

/**
 * One page of a browsed directory, plus the session that served it.
 */
export type DirListing = {
/**
 * The directory path inside the snapshot.
 */
path: string,
/**
 * The entries in this page.
 */
entries: Array<DirEntryView>,
/**
 * How many entries the directory holds in total.
 */
total: number,
/**
 * Index of the first entry in `entries` within the directory.
 */
offset: number,
/**
 * Maximum entries the server was asked to return.
 */
limit: number,
/**
 * The browse session this listing came from — the SPA reuses it for the
 * next navigation instead of paying for a new mover pod.
 */
session: SessionInfo, };
