// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectKind } from "./ObjectKind";

/**
 * One object a doctor check found something wrong with.
 */
export type DoctorObjectView = {
/**
 * Its kind.
 */
kind: ObjectKind,
/**
 * Its namespace; absent for a cluster-scoped object.
 */
namespace?: string | null,
/**
 * Its name.
 */
name: string,
/**
 * `true` when this object is part of why the check failed; `false` when
 * it is reported but does not count as red (a deliberate configuration,
 * a failure older than the window).
 */
failing: boolean,
/**
 * What is wrong with it, in the check's words.
 */
message: string,
/**
 * What to do, when the check knows something more specific than the
 * message says.
 */
fix?: string | null,
/**
 * RFC3339 instant it went wrong, when the check can date it.
 */
at?: string | null, };
