// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoctorCheckView } from "./DoctorCheckView";

/**
 * The full doctor report.
 */
export type DoctorReportView = {
/**
 * Every check that ran, in report order.
 */
checks: Array<DoctorCheckView>,
/**
 * The exit code `kubectl kopiur doctor` would have returned — `0` all
 * pass, `1` warnings, `2` failures.
 */
exitCode: number,
/**
 * RFC3339 timestamp of when the report was produced.
 */
ranAt: string, };
