// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One check from the doctor report.
 */
export type DoctorCheckView = {
/**
 * Stable check identifier, e.g. `crds-installed`.
 */
check: string,
/**
 * Human-readable name of the check.
 */
title: string,
/**
 * `Pass`, `Warn`, or `Fail`.
 */
outcome: string,
/**
 * What the check found.
 */
what?: string | null,
/**
 * Why that is a problem.
 */
why?: string | null,
/**
 * What to do about it.
 */
fix?: string | null, };
