// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoctorCheckView } from "./DoctorCheckView";

/**
 * The full doctor report.
 */
export type DoctorReportView = {
/**
 * Every check that ran, in report order.
 */
checks: Array<DoctorCheckView>,
/**
 * The exit code `kubectl kopiur doctor` would have returned: `0` when no
 * check failed — **warnings included** — and `1` when any check did.
 *
 * There is no third value. A warning deliberately is not a failure (an
 * RBAC-degraded check warns, and a restricted kubeconfig must not report a
 * broken cluster), so counting warnings from `checks` is the only way to
 * tell "all clear" from "could not fully verify".
 */
exitCode: number,
/**
 * RFC3339 timestamp of when the report was produced.
 */
ranAt: string, };
