// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of the cluster one doctor check actually looked at.
 *
 * A doctor run takes an optional namespace, and it narrows *some* checks and
 * not others — so a UI that prints "scoped to `media`" next to every row is
 * telling the operator something untrue about most of them. Which rows those
 * are is a fact about what each check reads, and the client had been keeping
 * its own copy of it. It was already wrong: `list_repos` lists `Repository`
 * inside the namespace but `ClusterRepository` cluster-wide, so the two
 * repository checks are neither purely one nor the other. That is what
 * [`Self::Mixed`] exists to say out loud.
 *
 * A closed enum, so a check added later cannot ship without stating its
 * scope, and the SPA narrows it with the same machinery it uses for every
 * other generated enum.
 */
export type DoctorScopeView = "namespace" | "installation" | "mixed";
