// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoctorObjectView } from "./DoctorObjectView";
import type { DoctorScopeView } from "./DoctorScopeView";

/**
 * One check from the doctor report.
 */
export type DoctorCheckView = {
/**
 * Stable check identifier, e.g. `crds-installed`.
 */
check: string,
/**
 * Human-readable name of the check.
 */
title: string,
/**
 * `Pass`, `Warn`, or `Fail`.
 */
outcome: string,
/**
 * How much of the cluster this check read, so the UI can say truthfully
 * what a namespace-scoped run covered instead of guessing from the title.
 */
scope: DoctorScopeView,
/**
 * What the check found.
 */
what?: string | null,
/**
 * Why that is a problem.
 */
why?: string | null,
/**
 * What to do about it.
 */
fix?: string | null,
/**
 * The objects the check found something wrong with, one entry each —
 * the same findings `what` puts in one sentence. Empty for a check that
 * is not about particular objects (the CRDs, the operator's own
 * Deployments) and for one that found nothing.
 */
objects: Array<DoctorObjectView>, };
