// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a [`GraphEdge`] stands for.
 */
export type EdgeKind = "snapshotReplication" | "repositoryReplication" | "seed" | "policyMembership" | "allowedNamespace";
