// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a directory entry is, inside a browse session.
 */
export type EntryKind = "file" | "dir" | "symlink" | { "other": {
/**
 * The entry type exactly as kopia reported it.
 */
raw: string, } };
