// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Kubernetes `Event`, projected for display next to the object it
 * concerns.
 */
export type EventRow = {
/**
 * RFC3339 timestamp of the event.
 */
time?: string | null,
/**
 * `Normal` or `Warning`.
 */
type?: string | null,
/**
 * The event's machine-readable reason.
 */
reason?: string | null,
/**
 * The event's human-readable message.
 */
message?: string | null,
/**
 * The object the event concerns, as `Kind/namespace/name`.
 */
regarding: string, };
