// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a run failed, in the terms the operator's own error classification uses.
 */
export type FailureView = {
/**
 * The classified kopia error, e.g. `RepositoryUnreachable`.
 */
kopiaErrorClass?: string | null,
/**
 * The failure message shown to the user.
 */
message?: string | null,
/**
 * Exit code of the mover process.
 */
exitCode?: number | null,
/**
 * Whether the operator considers a retry likely to succeed.
 */
retryRecommended?: boolean | null,
/**
 * The mover operation that failed, e.g. `snapshot`, `restore`.
 */
op?: string | null, };
