// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateSeverityView } from "./GateSeverityView";

/**
 * One admission or reconcile gate that is currently holding a resource back.
 *
 * Mirrors the blocking `status.conditions` entry that produced it, flattened
 * into the four fields the UI renders as a warning banner.
 */
export type GateHit = {
/**
 * The `status.conditions[].type` that is gating, e.g. `Ready`.
 */
condition: string,
/**
 * The `status.conditions[].reason`, e.g. `DeletionProtectionEngaged`.
 */
reason: string,
/**
 * How serious the gate is.
 */
severity: GateSeverityView,
/**
 * The `status.conditions[].message`, shown verbatim.
 */
message: string, };
