// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateSeverityView } from "./GateSeverityView";

/**
 * Static documentation for one gate the operator can apply, so the UI can
 * explain a gate it has never seen fire.
 */
export type GateDescriptor = {
/**
 * The CRD kind this gate applies to.
 */
scope: string,
/**
 * The `status.conditions[].type` that carries the gate.
 */
condition: string,
/**
 * The `status` value that means "blocked" for this condition — `True` for
 * some gates, `False` for others.
 */
blockedStatus: string,
/**
 * The `reason` this gate writes.
 */
reason: string,
/**
 * How serious the gate is. The same type [`GateHit::severity`] carries, so
 * the registry a gate is *documented* by and the hit it *produces* cannot
 * describe it differently.
 */
severity: GateSeverityView, };
