// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How loudly a gate should be reported.
 *
 * A closed enum rather than a string because the severity is *load-bearing on
 * both ends*: the SPA styles a banner from it, and the backend decides a
 * node's [`Health`] from it. A stringly-typed severity let one half of the
 * operator's own gate registry ship `Fail` while the other shipped `error`,
 * with nothing to catch it — the two projections now cannot disagree because
 * there is only one type to project onto.
 *
 * Mirrors `kopiur_api::gates::GateSeverity`, which has exactly these two
 * levels: a gate is either wedged work or a refusal that may well be the
 * configuration you asked for. There is no `info` — an informational gate
 * would not be a gate.
 */
export type GateSeverityView = "warning" | "error";
