// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateHit } from "./GateHit";
import type { Health } from "./Health";
import type { NodeKind } from "./NodeKind";

/**
 * One vertex of the repository topology graph.
 */
export type GraphNode = {
/**
 * Stable identifier used by [`GraphEdge::from`]/[`GraphEdge::to`], unique
 * within one [`RepositoryGraph`].
 */
id: string,
/**
 * What this node stands for.
 */
kind: NodeKind,
/**
 * `metadata.name` of the underlying object, or the backend/selector's
 * canonical name for synthetic nodes.
 */
name: string,
/**
 * `metadata.namespace`, absent for cluster-scoped and synthetic nodes.
 */
namespace?: string | null,
/**
 * Display label for the node, already disambiguated for rendering.
 */
label: string,
/**
 * Coarse health, from the object's conditions and phase.
 */
health: Health,
/**
 * True when the node is referenced by an edge but the object does not
 * exist — a dangling reference, drawn as a ghost.
 */
missing: boolean,
/**
 * For cluster repositories: true when `spec.allowedNamespaces` admits
 * every namespace rather than an explicit set.
 */
allowsAllNamespaces: boolean,
/**
 * For backend nodes: which backend variant this is (`s3`, `filesystem`, …).
 */
backendKind?: string | null,
/**
 * Gates currently holding this node's object back.
 */
gates: Array<GateHit>, };
