// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeKind } from "./EdgeKind";
import type { Health } from "./Health";

/**
 * One directed relationship between two [`GraphNode`]s.
 */
export type GraphEdge = {
/**
 * Stable identifier, unique within one [`RepositoryGraph`].
 */
id: string,
/**
 * [`GraphNode::id`] this edge starts at.
 */
from: string,
/**
 * [`GraphNode::id`] this edge ends at.
 */
to: string,
/**
 * What the relationship is.
 */
kind: EdgeKind,
/**
 * Optional edge label, e.g. the replication's cron schedule.
 */
label?: string | null,
/**
 * Coarse health of the relationship itself — a failing replication is a
 * failed edge between two healthy nodes.
 */
health: Health, };
