// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Repository.status.health` — the periodic connectivity probe.
 */
export type HealthProbeView = {
/**
 * RFC3339 timestamp of the most recent probe, successful or not.
 */
lastProbeAt?: string | null,
/**
 * RFC3339 timestamp of the most recent successful probe.
 */
lastHealthyAt?: string | null,
/**
 * Probe failures since the last success; drives the `Degraded` health.
 */
consecutiveProbeFailures?: number | null, };
