// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Health } from "./Health";

/**
 * How many objects of one kind are in one health state.
 */
export type HealthCount = {
/**
 * The state.
 */
health: Health,
/**
 * How many objects are in it.
 */
count: number, };
