// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse health of a node or edge, driving its color in the graph and its
 * badge in list views.
 */
export type Health = "healthy" | "degraded" | "failed" | "suspended" | "pending" | "unknown";
