// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the backend established the caller's identity.
 *
 * `Eq` + `Hash` because this is a field of the backend's `Identity`, which keys
 * the impersonating-client and `SubjectAccessReview` caches: two callers that
 * differ only in how they were authenticated must not share a cache entry.
 */
export type IdentitySource = "trustedHeaders" | "anonymous";
