// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthCount } from "./HealthCount";
import type { ObjectKind } from "./ObjectKind";

/**
 * One kind's objects in scope, split by health.
 */
export type KindTally = {
/**
 * The kind.
 */
kind: ObjectKind,
/**
 * Every object of this kind in scope (for snapshots, only the window).
 */
total: number,
/**
 * Non-zero states only, worst first: failed, degraded, pending, unknown,
 * suspended, healthy.
 */
byHealth: Array<HealthCount>,
/**
 * The caller may not list this kind in scope, so it was not counted:
 * `total` is 0 because nothing was read, not because there is nothing.
 * The other kinds are counted all the same.
 */
refused: boolean, };
