// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapshotRefView } from "./SnapshotRefView";

/**
 * Where a snapshot came from and where it has been copied to.
 */
export type Lineage = {
/**
 * The repository this snapshot was replicated in from, if any.
 */
copiedFromRepository?: string | null,
/**
 * The kopia manifest ID in the source repository.
 */
sourceManifestId?: string | null,
/**
 * `Snapshot` resources that are copies of this one.
 */
copies: Array<SnapshotRefView>, };
