// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManualRunView } from "./ManualRunView";
import type { RunStatusView } from "./RunStatusView";

/**
 * One row of the maintenance table — a `Maintenance` resource's two run
 * tracks plus any pending manual run.
 */
export type MaintenanceRow = {
/**
 * `metadata.namespace`.
 */
namespace: string,
/**
 * `metadata.name`.
 */
name: string,
/**
 * Repository this maintenance governs.
 */
repository: string,
/**
 * The owning repository, when this `Maintenance` was projected from a
 * repository's `spec.maintenance`.
 */
owner?: string | null,
/**
 * True when the operator owns this `Maintenance`; false when a user
 * authored it, in which case the operator honors it but never rewrites it.
 */
managedByRepository: boolean,
/**
 * The quick-maintenance track.
 */
quick: RunStatusView,
/**
 * The full-maintenance track.
 */
full: RunStatusView,
/**
 * A manual run the user requested, if one is pending or recent.
 */
manualRun?: ManualRunView | null, };
