// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepositoryRefBody } from "./RepositoryRefBody";

/**
 * Request a maintenance run right now.
 */
export type MaintenanceRunBody = {
/**
 * Namespace of the `Maintenance` resource.
 */
namespace: string,
/**
 * Name of the `Maintenance` resource; resolved from `repository` when
 * omitted.
 */
name?: string | null,
/**
 * The repository to maintain, when addressing it by repository rather than
 * by `Maintenance` name.
 */
repository?: RepositoryRefBody | null,
/**
 * `quick` or `full`.
 */
mode: string, };
