// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user-requested maintenance run.
 */
export type ManualRunView = {
/**
 * RFC3339 timestamp of when the run was requested.
 */
requestedAt?: string | null,
/**
 * `quick` or `full`.
 */
mode?: string | null,
/**
 * The run's current phase.
 */
phase?: string | null,
/**
 * RFC3339 timestamp of when the run finished.
 */
completedAt?: string | null, };
