// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { IdentitySource } from "./IdentitySource";

/**
 * The answer to "who am I" — what the UI shows in the account menu and uses to
 * decide which actions to offer.
 */
export type Me = {
/**
 * Username the backend will impersonate for this caller's requests.
 */
user: string,
/**
 * Groups the backend will impersonate alongside `user`.
 */
groups: Array<string>,
/**
 * Email address, when the authenticating proxy supplied one.
 */
email?: string | null,
/**
 * How `user`/`groups` were established.
 */
source: IdentitySource,
/**
 * Namespace the UI is scoped to, when it runs namespace-scoped rather than
 * cluster-wide.
 */
namespace?: string | null,
/**
 * What this identity is allowed to do.
 */
can: Capabilities, };
