// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A namespace that holds kopiur objects the caller may see.
 */
export type NamespaceSummary = {
/**
 * The namespace.
 */
name: string,
/**
 * How many namespaced kopiur objects in it the caller may see.
 */
objects: number, };
