// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a [`GraphNode`] stands for.
 */
export type NodeKind = "repository" | "clusterRepository" | "backend" | "policy" | "namespace" | "namespaceSelector";
