// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The nine kopiur kinds the console shows, as one closed vocabulary.
 *
 * The SPA keys each kind's identity (colour, glyph, label) on this, so a new
 * kind cannot reach the console without being given one.
 */
export type ObjectKind = "repository" | "clusterRepository" | "maintenance" | "snapshotPolicy" | "snapshotSchedule" | "snapshot" | "restore" | "repositoryReplication" | "snapshotReplication";
