// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * View of `Snapshot` `status.origin` — how the snapshot came to exist.
 */
export type OriginView = "scheduled" | "manual" | "discovered" | "adopted" | "replicated";
