// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KindTally } from "./KindTally";

/**
 * `GET /api/v1/overview` — the fleet by kind.
 */
export type OverviewView = {
/**
 * All nine kinds, in [`ObjectKind`] order, zero-total ones included.
 */
kinds: Array<KindTally>,
/**
 * Snapshots are counted over this many trailing hours.
 */
snapshotWindowHours: number,
/**
 * RFC3339 instant the tallies were taken.
 */
generatedAt: string, };
