// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One page of a listing, carrying the window that produced it so the SPA can
 * render "showing 21-40 of 137" without a second request.
 */
export type Page<T> = {
/**
 * The rows in this page.
 */
items: Array<T>,
/**
 * How many rows exist across all pages.
 */
total: number,
/**
 * Index of the first row in `items` within the full result set.
 */
offset: number,
/**
 * Maximum rows the server was asked to return.
 */
limit: number, };
