// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A namespaced reference to a `SnapshotPolicy`.
 */
export type PolicyRef = {
/**
 * `metadata.namespace` of the policy.
 */
namespace: string,
/**
 * `metadata.name` of the policy.
 */
name: string, };
