// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionView } from "./ConditionView";
import type { GateHit } from "./GateHit";
import type { PolicyRow } from "./PolicyRow";
import type { RepoVerificationView } from "./RepoVerificationView";
import type { RetentionView } from "./RetentionView";
import type { ScheduleRow } from "./ScheduleRow";
import type { SnapshotRow } from "./SnapshotRow";

/**
 * Everything the policy detail screen shows.
 */
export type PolicyDetail = {
/**
 * The same fields the table row shows.
 */
row: PolicyRow,
/**
 * The resolved kopia identity (`user@host:/path`) snapshots are written
 * under.
 */
identity?: string | null,
/**
 * The source paths the policy backs up.
 */
sources: Array<string>,
/**
 * `spec.retention` — the GFS rules.
 */
retention?: RetentionView | null,
/**
 * Per-repository verification state.
 */
verification: Array<RepoVerificationView>,
/**
 * Schedules that fire this policy.
 *
 * Exact, not approximate: a `policySelector` is evaluated with the same
 * matcher the operator's own schedule reconciler uses, `matchExpressions`
 * included.
 */
schedules: Array<ScheduleRow>,
/**
 * The most recent snapshots this policy produced.
 */
recentSnapshots: Array<SnapshotRow>,
/**
 * Gates currently holding this policy back.
 */
gates: Array<GateHit>,
/**
 * `status.conditions`.
 */
conditions: Array<ConditionView>, };
