// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the policies table.
 */
export type PolicyRow = {
/**
 * `metadata.namespace`.
 */
namespace: string,
/**
 * `metadata.name`.
 */
name: string,
/**
 * Repositories this policy writes into.
 */
repositories: Array<string>,
/**
 * True when the policy fans out to more than one repository.
 */
multiRepo: boolean,
/**
 * `spec.suspend`.
 */
suspended: boolean,
/**
 * RFC3339 timestamp of the most recent successful snapshot.
 */
lastSuccessfulSnapshot?: string | null,
/**
 * RFC3339 timestamp of the most recent successful verification.
 */
lastVerified?: string | null,
/**
 * How many non-deleted `Snapshot` resources this policy currently owns.
 */
activeSnapshotCount?: number | null, };
