// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An RFC 7807 `application/problem+json` body, extended with kopiur's
 * what/why/fix triple so the SPA can render an actionable error instead of a
 * status code.
 *
 * The three extension members mirror the message discipline the operator's own
 * `OpsError`/`thiserror` types follow: say what happened, why it happened, and
 * what the operator should do next.
 */
export type Problem = {
/**
 * Stable URI reference identifying the problem class, e.g.
 * `https://kopiur.dev/problems/forbidden`. Machine-readable; the SPA
 * switches on this, never on `title`.
 */
type: string,
/**
 * Short, human-readable summary of the problem class.
 */
title: string,
/**
 * HTTP status code repeated in the body, per RFC 7807.
 */
status: number,
/**
 * Human-readable explanation specific to this occurrence.
 */
detail: string,
/**
 * What happened, in the user's terms.
 */
what: string,
/**
 * Why it happened — the underlying cause.
 */
why: string,
/**
 * What to do about it — the remediation step.
 */
fix: string,
/**
 * URI reference identifying this specific occurrence, typically the
 * request path that produced it.
 */
instance?: string | null,
/**
 * The Kubernetes `Status.reason` (e.g. `Forbidden`, `NotFound`,
 * `Conflict`) when the failure came from the apiserver, so the SPA can
 * distinguish an RBAC denial from a missing object.
 */
kubeReason?: string | null, };
