// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * View of `RepositoryReplication`/`SnapshotReplication` `status.phase`.
 */
export type ReplicationPhaseView = "pending" | "replicating" | "succeeded" | "failed" | "suspended" | { "unknown": {
/**
 * The phase string exactly as the operator wrote it.
 */
raw: string, } };
