// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplicationKind } from "./ReplicationKind";

/**
 * A replication named with its kind and namespace, so a client never joins
 * on a bare name — two replications may share one across namespaces.
 */
export type ReplicationRef = {
/**
 * Which replication kind this is.
 */
kind: ReplicationKind,
/**
 * `metadata.namespace` of the replication.
 */
namespace: string,
/**
 * `metadata.name` of the replication.
 */
name: string, };
