// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trigger a replication run right now.
 */
export type ReplicationRunBody = {
/**
 * Namespace of the replication resource.
 */
namespace: string,
/**
 * Name of the replication resource.
 */
name: string,
/**
 * `RepositoryReplication` or `SnapshotReplication`, or the kebab tokens;
 * omit to detect by name.
 *
 * Detection reads both kinds and fails when one name exists in both — this
 * is how the caller says which one they meant, so the remediation on that
 * ambiguity is something the API can actually satisfy.
 */
kind?: string | null, };
