// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the two replication kinds a [`ReplicationRef`] names.
 */
export type ReplicationKind = "repositoryReplication" | "snapshotReplication";
