// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepositoryReplicationRow } from "./RepositoryReplicationRow";
import type { SnapshotReplicationRow } from "./SnapshotReplicationRow";

/**
 * Both replication tables, as `GET /api/v1/replications` answers them.
 *
 * The two kinds copy different things — one syncs a repository's blobs to a
 * bare backend, the other migrates selected snapshots between repository CRs —
 * so they keep separate row types and are returned side by side rather than
 * forced into a shared shape that would fit neither.
 *
 * Lives here rather than in the server crate even though it is an envelope: a
 * wire type declared next to its handler is a type `export_all` never emits,
 * and the SPA is forbidden from hand-writing a shape the server owns.
 */
export type ReplicationsView = {
/**
 * Whole-repository blob syncs.
 */
repository: Array<RepositoryReplicationRow>,
/**
 * Snapshot-level copies between repositories.
 */
snapshot: Array<SnapshotReplicationRow>, };
