// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * View of `Repository`/`ClusterRepository` `status.phase`.
 */
export type RepositoryPhaseView = "pending" | "initializing" | "ready" | "degraded" | "failed" | { "unknown": {
/**
 * The phase string exactly as the operator wrote it.
 */
raw: string, } };
