// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplicationPhaseView } from "./ReplicationPhaseView";

/**
 * One row of the repository-replications table.
 */
export type RepositoryReplicationRow = {
/**
 * `metadata.namespace`.
 */
namespace: string,
/**
 * `metadata.name`.
 */
name: string,
/**
 * Repository whose blobs are copied.
 */
source: string,
/**
 * Which backend variant the copy is written to.
 */
destinationBackend?: string | null,
/**
 * `spec.schedule.cron`.
 */
cron: string,
/**
 * `spec.suspend`.
 */
suspended: boolean,
/**
 * `status.phase`.
 */
phase?: ReplicationPhaseView | null,
/**
 * RFC3339 timestamp of the last successful replication.
 */
lastReplicated?: string | null,
/**
 * RFC3339 timestamp of the next computed run.
 */
nextScheduledAt?: string | null,
/**
 * Bytes the last run copied.
 */
lastReplicatedBytes?: number | null,
/**
 * Blobs the last run copied.
 */
lastReplicatedBlobs?: number | null, };
