// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Verification state for one repository a policy writes into.
 */
export type RepoVerificationView = {
/**
 * Name of the repository.
 */
repository: string,
/**
 * RFC3339 timestamp of the last successful verification there.
 */
lastVerified?: string | null, };
