// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogView } from "./CatalogView";
import type { ConditionView } from "./ConditionView";
import type { GateHit } from "./GateHit";
import type { HealthProbeView } from "./HealthProbeView";
import type { MaintenanceRow } from "./MaintenanceRow";
import type { PolicyRef } from "./PolicyRef";
import type { ReplicationRef } from "./ReplicationRef";
import type { RepositorySummary } from "./RepositorySummary";
import type { ScheduleRow } from "./ScheduleRow";
import type { SeedView } from "./SeedView";
import type { ServerView } from "./ServerView";
import type { SessionInfo } from "./SessionInfo";

/**
 * Everything the repository detail screen shows.
 */
export type RepositoryDetail = {
/**
 * The same fields the table row shows.
 */
summary: RepositorySummary,
/**
 * `status.resolved.identity.cluster` — the cluster identity component the
 * operator resolved for snapshots written here.
 */
identityCluster?: string | null,
/**
 * Catalog-scan results, when catalog discovery is enabled.
 */
catalog?: CatalogView | null,
/**
 * Health-probe results, when probing is enabled.
 */
health?: HealthProbeView | null,
/**
 * Repository-server state, when running in server mode.
 */
server?: ServerView | null,
/**
 * Seed/bootstrap state, when this repository was seeded from another.
 */
seed?: SeedView | null,
/**
 * The `Maintenance` resource governing this repository, managed or
 * externally authored.
 */
maintenance?: MaintenanceRow | null,
/**
 * Gates currently holding this repository back.
 */
gates: Array<GateHit>,
/**
 * `status.conditions`.
 */
conditions: Array<ConditionView>,
/**
 * Policies that write into this repository.
 */
policies: Array<PolicyRef>,
/**
 * Schedules that fire any policy writing into this repository, sorted by
 * namespace then name — the "fired by" end of its relationships.
 */
schedules: Array<ScheduleRow>,
/**
 * Replications that read from this repository.
 */
replicationsOut: Array<ReplicationRef>,
/**
 * Replications that write into this repository.
 */
replicationsIn: Array<ReplicationRef>,
/**
 * Browse sessions currently open against this repository.
 */
sessions: Array<SessionInfo>, };
