// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Health } from "./Health";
import type { RepositoryPhaseView } from "./RepositoryPhaseView";

/**
 * One row of the repositories table — `Repository` and `ClusterRepository`
 * projected into a single shape.
 */
export type RepositorySummary = {
/**
 * `Repository` or `ClusterRepository`.
 */
kind: string,
/**
 * The `{kind}` URL segment for this row — `repository` or
 * `cluster-repository`.
 *
 * Here so the SPA links to `/repositories/{kindPath}/{name}` and
 * `DELETE /repositories/{kindPath}/{name}/session` without a local
 * CRD-kind-to-segment mapping table. [`Self::kind`] is the CRD kind for
 * display; this is the routing token, and the two differ in case and
 * punctuation. Both routes also *accept* [`Self::kind`] itself, so a client
 * that ignores this field still works — it is the canonical spelling, not
 * the only one.
 *
 * `RepositoryDetail` carries it as `summary.kindPath`: one field, so the
 * segment a row links with and the segment a detail screen links with
 * cannot drift.
 */
kindPath: string,
/**
 * `metadata.name`.
 */
name: string,
/**
 * `metadata.namespace`; absent for `ClusterRepository`.
 */
namespace?: string | null,
/**
 * `status.phase`.
 */
phase?: RepositoryPhaseView | null,
/**
 * Coarse health derived from phase and conditions.
 */
health: Health,
/**
 * Which `spec.backend` variant this repository uses (`s3`, `filesystem`, …).
 */
backend?: string | null,
/**
 * `spec.mode` — `ReadWrite` or `ReadOnly`.
 *
 * The same text `kubectl kopiur status` prints in its `MODE` column and
 * `/api/v1/status` ships in its report, so one API cannot mean two things
 * by `mode`. How clients *reach* the repository is [`Self::server_backed`].
 */
mode: string,
/**
 * Whether a kopia repository server fronts this repository.
 *
 * `false` means every mover talks to the storage backend directly. Split
 * from [`Self::mode`] because access path and access rights are
 * independent: a read-only repository can be server-backed or direct, and
 * a UI that conflated them could not say which.
 */
serverBacked: boolean,
/**
 * `spec.suspend`.
 */
suspended: boolean,
/**
 * `status.stats.snapshotCount`.
 */
snapshotCount?: number | null,
/**
 * `status.stats.totalSizeBytes`.
 */
totalSizeBytes?: number | null,
/**
 * `status.stats.indexBlobCount`.
 */
indexBlobCount?: number | null,
/**
 * RFC3339 timestamp of the last successful stats observation.
 */
lastObservedAt?: string | null,
/**
 * `status.server.endpoint`, when running in repository-server mode.
 */
serverEndpoint?: string | null,
/**
 * For `ClusterRepository`: how many namespaces `spec.allowedNamespaces`
 * currently admits.
 */
allowedNamespaceCount?: number | null, };
