// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphEdge } from "./GraphEdge";
import type { GraphNode } from "./GraphNode";

/**
 * The whole repository topology, as of one point in time.
 */
export type RepositoryGraph = {
/**
 * Every vertex.
 */
nodes: Array<GraphNode>,
/**
 * Every directed relationship between them.
 */
edges: Array<GraphEdge>,
/**
 * RFC3339 timestamp of when the server assembled this graph.
 */
generatedAt: string, };
