// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapshotRefView } from "./SnapshotRefView";

/**
 * `Restore.status.resolved` — the source pinned at admission.
 *
 * The two fields the row already carries (the repository and the kopia
 * manifest id) are not repeated here: one value, one place.
 */
export type RestoreSourceView = {
/**
 * `Snapshot` when the source resolved to a kopia snapshot, `NoSnapshot`
 * when it matched none and `onMissingSnapshot: Continue` chose an empty
 * volume — which is a *successful* restore of nothing, not a failure.
 */
resolution?: string | null,
/**
 * The concrete `Snapshot` resource the source resolved to, when there is
 * one to navigate to.
 */
snapshot?: SnapshotRefView | null,
/**
 * RFC3339 timestamp the source was pinned at.
 */
pinnedAt?: string | null,
/**
 * The resolved kopia identity (`user@host:/path`) the data is read from.
 */
identity?: string | null, };
