// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionView } from "./ConditionView";
import type { FailureView } from "./FailureView";
import type { RestoreRow } from "./RestoreRow";
import type { RestoreSourceView } from "./RestoreSourceView";
import type { RestoreTargetView } from "./RestoreTargetView";

/**
 * Everything the restore detail screen shows.
 *
 * # What is deliberately not here
 *
 * **A progress percentage.** `Restore.status.progress` carries
 * `bytesRestored`/`filesRestored` and no total to divide by, so there is
 * nothing to compute one from; the two counters already ride
 * [`RestoreRow`]. A `percent` field would have to be invented, and a restore
 * that showed a fabricated "80%" is worse than one that shows bytes.
 *
 * **Per-claim byte counts.** `RestoreClaimStatus` records a phase and a
 * message, not counters, so a populator fan-out's progress is per-claim
 * *state* — which is what [`RestoreClaimView`] already carries on the row.
 */
export type RestoreDetail = {
/**
 * The same fields the table row shows, the per-claim rows included.
 */
row: RestoreRow,
/**
 * `status.resolved` — what the source was pinned to at admission.
 *
 * Absent until resolution runs. A restore never re-resolves, so this is
 * what the run will actually read, not what the spec asks for.
 */
source?: RestoreSourceView | null,
/**
 * `status.target` — where the data is actually being written.
 */
target?: RestoreTargetView | null,
/**
 * `status.conditions`.
 */
conditions: Array<ConditionView>,
/**
 * Failure detail, present when the run failed.
 */
failure?: FailureView | null,
/**
 * Last lines of the mover Job's log, redacted. Empty when the run wrote
 * none.
 */
logTail: Array<string>, };
