// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * View of `Restore` `status.phase`.
 */
export type RestorePhaseView = "pending" | "resolving" | "restoring" | "completed" | "failed" | { "unknown": {
/**
 * The phase string exactly as the operator wrote it.
 */
raw: string, } };
