// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which snapshot to restore, as an externally-tagged union — exactly one
 * variant, matching the `Restore` CRD's own "exactly one of" source surface.
 */
export type RestoreSourceBody = { "snapshotRef": {
/**
 * `metadata.name` of the `Snapshot`.
 */
name: string,
/**
 * `metadata.namespace` of the `Snapshot`; defaults to the restore's
 * own namespace.
 */
namespace?: string | null, } } | { "fromPolicy": {
/**
 * `metadata.name` of the `SnapshotPolicy`.
 */
name: string,
/**
 * `metadata.namespace` of the policy; defaults to the restore's own
 * namespace.
 */
namespace?: string | null,
/**
 * RFC3339 instant to pick the newest snapshot at or before.
 */
asOf?: string | null,
/**
 * Step back this many snapshots from the newest — `0` is the latest.
 */
offset?: number | null, } } | { "identity": {
/**
 * Kopia username component of the identity.
 */
username: string,
/**
 * Kopia hostname component of the identity.
 */
hostname: string,
/**
 * Source path component; required when the identity has more than one.
 */
sourcePath?: string | null,
/**
 * A specific kopia manifest ID; the newest is used when omitted.
 */
snapshotId?: string | null, } };
