// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RestoreClaimView } from "./RestoreClaimView";
import type { RestorePhaseView } from "./RestorePhaseView";

/**
 * One row of the restores table.
 */
export type RestoreRow = {
/**
 * `metadata.namespace`.
 */
namespace: string,
/**
 * `metadata.name`.
 */
name: string,
/**
 * `status.phase`.
 */
phase?: RestorePhaseView | null,
/**
 * Which `spec.source` variant this restore uses.
 */
sourceKind?: string | null,
/**
 * Which `spec.target` variant this restore uses.
 */
targetKind: string,
/**
 * Repository the snapshot is read from.
 */
repository?: string | null,
/**
 * The resolved kopia manifest ID being restored.
 */
kopiaSnapshotId?: string | null,
/**
 * `status.startTime` as RFC3339.
 */
startTime?: string | null,
/**
 * `status.endTime` as RFC3339.
 */
endTime?: string | null,
/**
 * Bytes written to the target so far.
 */
bytesRestored?: number | null,
/**
 * Files written to the target so far.
 */
filesRestored?: number | null,
/**
 * Per-claim progress, one entry per target PVC.
 */
claims: Array<RestoreClaimView>, };
