// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-PVC progress within one restore.
 */
export type RestoreClaimView = {
/**
 * Name of the target `PersistentVolumeClaim`.
 */
pvc: string,
/**
 * The claim's restore phase.
 */
phase: string,
/**
 * Detail for this claim, typically a failure reason.
 */
message?: string | null, };
