// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepositoryRefBody } from "./RepositoryRefBody";
import type { RestoreSourceBody } from "./RestoreSourceBody";
import type { RestoreTargetBody } from "./RestoreTargetBody";

/**
 * Create a `Restore`.
 */
export type RestoreBody = {
/**
 * Namespace to create the `Restore` in.
 */
namespace: string,
/**
 * Where the data comes from.
 */
source: RestoreSourceBody,
/**
 * Where the data goes.
 */
target: RestoreTargetBody,
/**
 * Repository to read from; inferred from the source when omitted.
 */
repository?: RepositoryRefBody | null,
/**
 * Name for the new `Restore`; the server generates one when omitted.
 */
name?: string | null,
/**
 * Overwrite files that already exist on the target.
 */
overwrite?: boolean | null,
/**
 * Which kopia source path to read FROM, overriding the one kopiur would
 * derive.
 *
 * A source *selector*, not a subtree filter: it picks which of a
 * repository's kopia sources the snapshot is pulled from, and does not
 * change what is written or restore only part of a snapshot. Mirrors the
 * CRD's own `fromPolicy.sourcePath` and `identity.sourcePath`, which is
 * where it lands.
 *
 * Needed when the derivation is ambiguous or wrong — most often a
 * multi-PVC `pvcSelector` policy, where each member wrote its own
 * `/pvc/<name>` source and the restore has to say which one it wants.
 * Meaningless with a `snapshotRef` source, which already pins the path its
 * `Snapshot` was written from.
 */
sourcePath?: string | null, };
