// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a restore writes, as an externally-tagged union — exactly one variant.
 */
export type RestoreTargetBody = { "pvcRef": {
/**
 * `metadata.name` of the claim.
 */
name: string, } } | { "pvc": {
/**
 * `metadata.name` for the new claim.
 */
name: string,
/**
 * Storage class for the new claim; the cluster default when omitted.
 */
storageClassName?: string | null,
/**
 * Requested size, as a Kubernetes quantity (e.g. `10Gi`).
 */
size: string, } };
