// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Restore.status.target` — the PVC the data lands in.
 */
export type RestoreTargetView = {
/**
 * Name of the `PersistentVolumeClaim` actually written to, created or
 * pre-existing.
 *
 * A name rather than a reference: the controller writes this claim without
 * a namespace because a restore only ever writes into its own, which is
 * `RestoreDetail.row.namespace`.
 */
pvc?: string | null,
/**
 * The populator handshake's prime PVC, for a `target.populator` restore.
 */
pvcPrime?: string | null, };
