// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `SnapshotPolicy.spec.retention` — the GFS rules, `None` meaning unset.
 */
export type RetentionView = {
/**
 * Most recent snapshots to keep regardless of age.
 */
keepLatest?: number | null,
/**
 * Hourly slots to keep.
 */
keepHourly?: number | null,
/**
 * Daily slots to keep.
 */
keepDaily?: number | null,
/**
 * Weekly slots to keep.
 */
keepWeekly?: number | null,
/**
 * Monthly slots to keep.
 */
keepMonthly?: number | null,
/**
 * Annual slots to keep.
 */
keepAnnual?: number | null, };
