// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyRef } from "./PolicyRef";
import type { RetentionBucket } from "./RetentionBucket";

/**
 * Every snapshot competing for the same retention buckets as one snapshot,
 * with the verdict today's GFS selection gives each.
 *
 * This is what `GET /api/v1/snapshots/{namespace}/{name}/retention` answers,
 * and it is the screen where a misreading costs a restore point — so the
 * population and the bucketing are the *prune's own*
 * (`kopiur_api::retention::retention_buckets`), never a second implementation
 * that could disagree with what the operator will actually delete.
 */
export type RetentionPlan = {
/**
 * One entry per bucket the policy's population splits into, keyed by the
 * bucket key, ordered by that key.
 *
 * Buckets are independent: a fan-out policy over seven PVCs has seven, and
 * no snapshot in one can displace a snapshot in another. That independence
 * is the whole reason this is a list of buckets rather than one list of
 * candidates.
 */
buckets: Array<RetentionBucket>,
/**
 * The `SnapshotPolicy` the plan was computed from.
 */
policy: PolicyRef,
/**
 * RFC3339 timestamp the plan was computed at. GFS verdicts move as time
 * passes, so a plan is an answer about a moment.
 */
computedAt: string,
/**
 * True when the policy configures no retention at all.
 *
 * Nothing is pruned by GFS in that case — the operator only runs a
 * selection when a retention policy exists — so every candidate is reported
 * `kept: true` with no `rules`. Rendering an unbounded plan as "everything
 * will be deleted" (which is what running an empty policy through the
 * selection kernel would literally say) is the exact inversion this flag
 * exists to prevent.
 */
unbounded: boolean, };
