// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetentionCandidate } from "./RetentionCandidate";

/**
 * One retention bucket and the snapshots competing inside it.
 */
export type RetentionBucket = {
/**
 * The bucket key the controller groups by: the backup source, plus the
 * pinned repository while the policy is multi-repo. Empty for an un-fanned,
 * single-repository policy, which has exactly one bucket.
 *
 * Opaque — a join key and a grouping label, not a path to parse.
 */
key: string,
/**
 * The bucket's candidates, newest first, ties broken by name — the same
 * order the selection kernel walks them in.
 */
candidates: Array<RetentionCandidate>, };
