// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One snapshot's place in its retention bucket.
 */
export type RetentionCandidate = {
/**
 * `metadata.namespace`.
 */
namespace: string,
/**
 * `metadata.name`.
 */
name: string,
/**
 * The end time GFS buckets on: `status.timing.endTime`, falling back to
 * `metadata.creationTimestamp`. Never absent — a row with neither is not in
 * the GFS population and so is not a candidate at all.
 */
endTime: string,
/**
 * True when today's selection keeps this snapshot.
 */
kept: boolean,
/**
 * Which rules hold it and in which slot, e.g. `keepDaily slot 3`; `pinned`
 * alone for a pin. Empty when it is pruned. Same strings as
 * [`RetentionPreview::reasons`].
 */
rules: Array<string>,
/**
 * `spec.pin` — exempt from GFS pruning entirely.
 *
 * The *spec*, which is what the prune reads. During an unpin, `status.pinned`
 * still says `true` and reporting that would promise a keep the next prune
 * will not honour.
 */
pinned: boolean,
/**
 * True for the snapshot the request was about, so the SPA can highlight its
 * row among its competitors.
 */
subject: boolean, };
