// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the governing GFS retention would keep this snapshot right now, and
 * which rules say so.
 */
export type RetentionPreview = {
/**
 * True when at least one retention rule keeps the snapshot.
 */
kept: boolean,
/**
 * The rules that hold it, each with the slot it occupies in that rule's
 * window — `keepDaily slot 3` means the third-newest day `keepDaily` keeps,
 * so a reader can see how close the snapshot is to ageing out.
 *
 * `pinned` appears alone, without a slot: a pin is not a bucket slot, it is
 * an exemption from bucketing.
 *
 * Empty when the snapshot is pruned. The same strings, from the same
 * function, as [`RetentionCandidate::rules`].
 */
reasons: Array<string>,
/**
 * RFC3339 timestamp the preview was computed at — the answer moves as time
 * passes, so the UI shows when it was true.
 */
computedAt: string, };
