// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One maintenance track's run history.
 */
export type RunStatusView = {
/**
 * RFC3339 timestamp of the last run.
 */
lastRunAt?: string | null,
/**
 * RFC3339 timestamp of the next computed run.
 */
nextScheduledAt?: string | null,
/**
 * Failures since the last success.
 */
consecutiveFailures: number,
/**
 * Bytes the last run reclaimed by dropping unreachable content.
 */
lastContentReclaimedBytes?: number | null, };
