// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trigger a catalog scan of a repository.
 */
export type ScanCatalogBody = {
/**
 * `Repository` or `ClusterRepository`.
 */
kind: string,
/**
 * `metadata.namespace`; omitted for `ClusterRepository`.
 */
namespace?: string | null,
/**
 * `metadata.name`.
 */
name: string, };
