// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the schedules table.
 */
export type ScheduleRow = {
/**
 * `metadata.namespace`.
 */
namespace: string,
/**
 * `metadata.name`.
 */
name: string,
/**
 * The single policy this schedule fires, when it names one directly.
 */
policy?: string | null,
/**
 * The label selector this schedule fires by, when it selects policies.
 */
policySelector?: string | null,
/**
 * `spec.schedule.cron`, including any `H` jitter token as written.
 */
cron: string,
/**
 * `spec.schedule.timezone`.
 */
timezone?: string | null,
/**
 * `spec.suspend`.
 */
suspended: boolean,
/**
 * RFC3339 timestamp of the last fire.
 */
lastFire?: string | null,
/**
 * RFC3339 timestamp of the next computed fire.
 */
nextFire?: string | null,
/**
 * Name of the `Snapshot` the last fire produced.
 */
lastSnapshot?: string | null,
/**
 * Failures since the last success; bounded by `failedJobsHistoryLimit`.
 */
consecutiveFailures: number, };
