// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Repository.status.seed` — how this repository was bootstrapped.
 */
export type SeedView = {
/**
 * Which seeding strategy ran.
 */
mode?: string | null,
/**
 * The repository that was seeded from.
 */
source?: string | null,
/**
 * RFC3339 timestamp of when seeding completed.
 */
seededAt?: string | null,
/**
 * How many snapshots the seed copied across.
 */
snapshotsCopied?: number | null, };
