// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Repository.status.server` — the kopia repository server, when enabled.
 */
export type ServerView = {
/**
 * Address clients connect to.
 */
endpoint?: string | null,
/**
 * Whether the server admits writes.
 */
readOnly?: boolean | null,
/**
 * How the server authenticates clients.
 */
authMode?: string | null, };
