// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A browse session: a long-lived mover Job the UI execs into to read a
 * snapshot's contents.
 */
export type SessionInfo = {
/**
 * Namespace the session's Job runs in.
 */
namespace: string,
/**
 * Name of the session's Job.
 */
job: string,
/**
 * Name of the Job's pod, once scheduled.
 *
 * Populated by the browse endpoints, which have to resolve the pod anyway
 * to exec into it. Always **absent** on the sessions listed by
 * `RepositoryDetail.sessions`: naming the pod there would cost a `pods`
 * LIST per repository detail view to show a string nothing navigates by.
 */
pod?: string | null,
/**
 * True when an existing session was reused rather than a new one started.
 */
reused: boolean,
/**
 * RFC3339 timestamp of when the session will be reaped if left idle.
 */
expiresAt?: string | null,
/**
 * The largest single file `GET …/file` will stream, in bytes, as this
 * deployment is configured (`KOPIUR_UI_MAX_DOWNLOAD_BYTES`).
 *
 * Published so the file table can disable an oversized entry *with the
 * reason* before the user clicks. This is a second gate, not the gate: the
 * server still refuses an oversized download with a `413`
 * `download-too-large`. But a download is a top-level navigation, so that
 * refusal is rendered by the browser as a tab full of JSON — the SPA never
 * sees it and cannot turn it into a message.
 *
 * A `DirEntryView.size` of `null` means kopia reported no size, which is
 * the `422` `download-size-unknown` case: not comparable against this, and
 * not the same as zero.
 */
downloadMaxBytes: number,
/**
 * The largest kopia JSON manifest the server will buffer while walking the
 * snapshot, in bytes (`KOPIUR_UI_MAX_MANIFEST_BYTES`).
 *
 * This is what a `422` `directory-too-large` / `catalog-too-large` is
 * measured against — a *listing* bound, not a download bound — so the SPA
 * can explain a refused directory rather than reporting it as empty.
 */
manifestMaxBytes: number, };
