// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Open a browse session.
 */
export type SessionCreateBody = {
/**
 * How long the session may sit idle before it is reaped; the server's
 * default applies when omitted.
 */
ttlSeconds?: number | null, };
