// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A namespaced reference to a `Snapshot`.
 */
export type SnapshotRefView = {
/**
 * `metadata.namespace` of the snapshot.
 */
namespace: string,
/**
 * `metadata.name` of the snapshot.
 */
name: string, };
