// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OriginView } from "./OriginView";
import type { SnapshotPhaseView } from "./SnapshotPhaseView";

/**
 * One row of the snapshots table.
 */
export type SnapshotRow = {
/**
 * `metadata.namespace`.
 */
namespace: string,
/**
 * `metadata.name`.
 */
name: string,
/**
 * `status.phase`.
 */
phase?: SnapshotPhaseView | null,
/**
 * `status.origin`.
 */
origin?: OriginView | null,
/**
 * Name of the `SnapshotPolicy` this snapshot was taken under.
 */
policy?: string | null,
/**
 * Name of the repository the snapshot lives in.
 */
repository?: string | null,
/**
 * `status.kopiaSnapshotId` — the kopia manifest ID.
 */
kopiaSnapshotId?: string | null,
/**
 * The resolved kopia identity (`user@host:/path`) the snapshot was written
 * under.
 */
identity?: string | null,
/**
 * `status.startTime` as RFC3339.
 */
startTime?: string | null,
/**
 * `status.endTime` as RFC3339.
 */
endTime?: string | null,
/**
 * Logical size of the snapshotted tree.
 */
sizeBytes?: number | null,
/**
 * Bytes this snapshot actually added to the repository after dedup.
 */
bytesNew?: number | null,
/**
 * Files considered.
 */
filesTotal?: number | null,
/**
 * Files kopia could not read.
 */
filesFailed?: number | null,
/**
 * Whether the kopia manifest carries a retention pin, exempting it from
 * GFS pruning.
 */
pinned: boolean,
/**
 * `spec.deletionPolicy` — `Delete`, `Retain`, or `Orphan`.
 *
 * **Absent means the CR sets none, and must not be rendered as a default.**
 * The schema carries no `default:` — deliberately, because the effective
 * policy is context-dependent: a produced backup behaves as `Delete`, a
 * *discovered* one is forced to `Retain`, and which of those applies is the
 * operator's decision at delete time, not a value this field mirrors. A UI
 * that filled the blank with "Delete" would tell the owner of a discovered
 * snapshot that confirming would destroy data the operator will in fact
 * keep — and a UI that filled it with "Retain" would say the opposite to
 * everyone else.
 *
 * Render an absent value as "not set (the operator decides)" and say what
 * the deletion will do only when this field says it.
 */
deletionPolicy?: string | null,
/**
 * For replicated snapshots: the repository the copy came from.
 */
copiedFrom?: string | null, };
