// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Take a snapshot right now under an existing `SnapshotPolicy`.
 */
export type SnapshotNowBody = {
/**
 * Namespace of the policy, and of the `Snapshot` to create.
 */
namespace: string,
/**
 * Name of the `SnapshotPolicy` to snapshot under.
 */
policy: string,
/**
 * Name for the new `Snapshot`; the server generates one when omitted.
 */
name?: string | null,
/**
 * Extra kopia tags to attach, as `(key, value)` pairs.
 */
tags: Array<[string, string]>,
/**
 * Pin the resulting kopia manifest, exempting it from GFS pruning.
 */
pin: boolean,
/**
 * Free-text description recorded on the `Snapshot`.
 */
description?: string | null,
/**
 * Restrict a multi-repository policy to this one repository; omit to fan
 * out to all of them.
 */
repository?: string | null, };
