// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * View of `Snapshot` `status.phase`.
 */
export type SnapshotPhaseView = "pending" | "running" | "succeeded" | "failed" | "deleting" | "discovered" | "unchanged" | { "unknown": {
/**
 * The phase string exactly as the operator wrote it.
 */
raw: string, } };
