// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionView } from "./ConditionView";
import type { FailureView } from "./FailureView";
import type { GateHit } from "./GateHit";
import type { Lineage } from "./Lineage";
import type { RetentionPreview } from "./RetentionPreview";
import type { SnapshotRow } from "./SnapshotRow";
import type { SnapshotStatsView } from "./SnapshotStatsView";

/**
 * Everything the snapshot detail screen shows.
 */
export type SnapshotDetail = {
/**
 * The same fields the table row shows.
 */
row: SnapshotRow,
/**
 * Full kopia upload counters, when the run recorded them.
 */
stats?: SnapshotStatsView | null,
/**
 * Wall-clock duration between `startTime` and `endTime`.
 */
durationSeconds?: number | null,
/**
 * The source paths the snapshot covered.
 */
sources: Array<string>,
/**
 * Where this snapshot came from and where it has been copied to.
 */
lineage: Lineage,
/**
 * Whether the governing retention policy would keep this snapshot today.
 */
retentionPreview?: RetentionPreview | null,
/**
 * Failure detail, present when the run failed.
 */
failure?: FailureView | null,
/**
 * Last lines of the mover Job's log.
 */
logTail: Array<string>,
/**
 * `status.conditions`.
 */
conditions: Array<ConditionView>,
/**
 * Gates currently holding this snapshot back.
 */
gates: Array<GateHit>,
/**
 * Whether the UI may open a browse session against this snapshot.
 */
browsable: boolean,
/**
 * Why browsing is unavailable, when `browsable` is false.
 */
browseBlocker?: string | null, };
