// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Snapshot.status.stats` — kopia's upload counters for one run.
 */
export type SnapshotStatsView = {
/**
 * Logical size of the snapshotted tree.
 */
sizeBytes?: number | null,
/**
 * Bytes added to the repository after dedup.
 */
bytesNew?: number | null,
/**
 * Files seen for the first time.
 */
filesNew?: number | null,
/**
 * Files whose contents changed since the previous snapshot.
 */
filesModified?: number | null,
/**
 * Files reused unchanged from the previous snapshot.
 */
filesUnchanged?: number | null,
/**
 * Files kopia could not read.
 */
filesFailed?: number | null, };
