// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplicationPhaseView } from "./ReplicationPhaseView";

/**
 * One row of the snapshot-replications table.
 */
export type SnapshotReplicationRow = {
/**
 * `metadata.namespace`.
 */
namespace: string,
/**
 * `metadata.name`.
 */
name: string,
/**
 * Repository snapshots are read from.
 */
source: string,
/**
 * Repository snapshots are copied into.
 */
destination: string,
/**
 * `spec.schedule.cron`.
 */
cron: string,
/**
 * `spec.suspend`.
 */
suspended: boolean,
/**
 * `status.phase`.
 */
phase?: ReplicationPhaseView | null,
/**
 * RFC3339 timestamp of the last successful replication.
 */
lastReplicated?: string | null,
/**
 * Kopia identities the last run's selector matched.
 */
identitiesSelected?: number | null,
/**
 * Snapshots the last run copied.
 */
snapshotsCopied?: number | null,
/**
 * Snapshots the last run skipped because the destination already had them.
 */
alreadyPresent?: number | null,
/**
 * Snapshots the last run failed to copy.
 */
failed?: number | null,
/**
 * Snapshots the last run pruned from the destination.
 */
pruned?: number | null, };
