// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The dashboard's top-level status, wrapping the `kopiur-ops` status report
 * verbatim.
 */
export type StatusOverview = {
/**
 * The `kopiur_ops::status::StatusReport` as JSON, passed straight through.
 *
 * Deliberately opaque on the wire (`unknown` in TypeScript): the report is
 * the CLI's own shape and evolves with it, so pinning a second copy of it
 * here would guarantee drift. The SPA narrows it at the point of use.
 */
report: unknown,
/**
 * RFC3339 timestamp of when the server assembled the report, so relative
 * times ("2 minutes ago") are computed against the server's clock.
 */
now: string, };
