// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Suspend or resume a resource by flipping its `spec.suspend`.
 */
export type SuspendBody = {
/**
 * CRD kind of the resource to flip.
 */
kind: string,
/**
 * `metadata.namespace`; omitted for cluster-scoped kinds.
 */
namespace?: string | null,
/**
 * `metadata.name`.
 */
name: string,
/**
 * `true` to suspend, `false` to resume. Explicit rather than a toggle so
 * two concurrent clients cannot flip each other's intent.
 */
suspend: boolean, };
